[supabase]
url = "https://lzdiatqxbvgqiswywpts.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6ZGlhdHF4YnZncWlzd3l3cHRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODczMzE2ODAsImV4cCI6MjEwMjkwNzY4MH0.SsWdSaUFaAmjwgMnR8eo8CJT4fPs31oZFFY52-1w668"